# Generated by Django 2.2.7 on 2021-04-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
