# Generated by Django 3.1.7 on 2021-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('admin', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
